### ISSUE TITLE
Add school quadratic equations realisation

### ISSUE THREAD

**Issue by TechnomageLiloi** [TechnomageLiloi/MathAlg#2]
# Task

Add realisation of quadratic equation's solve (without complex numbers) with testing

# Jobs

- [x] Add algorithm
  - [x] Add text: two roots
  - [x] Add text: one roots
  - [x] Add text: zero roots
  - [x] Add class
- [x] Add solution
  - [x] Add text: two roots
  - [x] Add text: one roots
  - [x] Add text: zero roots
  - [x] Add class

- [x] Public
